# -*- coding: utf-8 -*-
"""vivek

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cT91y5rEnQolCMp-9pgc7aXkCCwd7Bi

OBJECTIVE: Train the model and save teh model so that for later use of the model we do not need to run the program again
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

url="https://raw.githubusercontent.com/vivekpenuli/anvil-deploy/master/hiring.csv"
dataset=pd.read_csv(url)

dataset['experience'].fillna(0, inplace=True)

dataset['test_score(out of 10)'].fillna(dataset['test_score(out of 10)'].mean(), inplace=True)

X = dataset.iloc[:, :3]

#Converting words to integer values
def convert_to_int(word):
    word_dict = {'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8,
                'nine':9, 'ten':10, 'eleven':11, 'twelve':12, 'zero':0, 0: 0}
    return word_dict[word]

X['experience'] = X['experience'].apply(lambda x : convert_to_int(x))

y = dataset.iloc[:, -1]

from sklearn.linear_model import LinearRegression
model = linear_model.LinearRegression()

model.fit(X, y)

print(model.predict([[2, 9, 6]]))

import pickle

pickle.dump(model, open('vivmodel.pkl','wb'))

model1 = pickle.load(open('vivmodel.pkl','rb'))

print(model1.predict([[2, 9, 6]]))